apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
  labels:
    app: multi-container-demo
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  - name: config-volume
    emptyDir: {}

  initContainers:
  - name: config-setup
    image: busybox:1.35
    command: ['sh', '-c']
    args:
    - |
      echo "Initializing configuration..."
      echo "server_name=web-app" > /config/app.conf
      echo "log_level=info" >> /config/app.conf
      echo "port=8080" >> /config/app.conf
    volumeMounts:
    - name: config-volume
      mountPath: /config

  containers:
  - name: web-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: config-volume
      mountPath: /etc/app-config
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Starting web app..."
      ls /etc/app-config/
      cat /etc/app-config/app.conf
      nginx -g 'daemon off;'

  - name: log-sidecar
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Log sidecar running..."
      while true; do
        if [ -f /var/log/nginx/access.log ]; then
          echo "=== Logs ==="
          tail -n 5 /var/log/nginx/access.log
        else
          echo "Waiting for access.log..."
        fi
        sleep 10
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
